package com.tricon.evc.enums;


public enum Capabilities {
	CHARGING_PROFILE_CAPABLE,
	CHARGING_PREFERENCES_CAPABLE,
	CREDIT_CARD_PAYABLE,
	DEBIT_CARD_PAYABLE,
	REMOTE_START_STOP_CAPABLE,
	RESERVABLE,
	RFID_READER,
	TOKEN_GROUP_CAPABLE,
	UNLOCK_CAPABLE;

}
