package com.tricon.evc.enums;

public enum EvseCapabilites {
  CHARGING_PROFILE_CAPABLE,
  CHARGING_PREFERENCES_CAPABLE,
  CREDIT_CARD_PAYBLE,
  DEBIT_CARD_PAYBLE,
  REMOTE_START_STOP_CAPABLE,
  RESERVABLE,
  RFID_READER;

}
